name: Build java application
on:
    workflow_dispatch:
     inputs:
        job_name:
            description: 'Enter the job name'
            required: true
            type: choice
            options:
                - job1_build
                - job2_codecoverage
jobs:
    job1_build:
        if: ${{ github.event.inputs.job_name == 'job1_build' }}
        runs-on: ubuntu-latest
        steps:
            - name: clone the repository
              uses: actions/checkout@v6
            - name: install java on runner
              uses: actions/setup-java@v5
              with:
                    java-version: '17'
                    distribution: 'temurin'
            - name: build java code
              run: mvn clean package
    job2_codecoverage:
        if: ${{ github.event.inputs.job_name == 'job2_codecoverage' }}
        runs-on: ubuntu-latest
        steps:
            - name: clone the repository
              uses: actions/checkout@v6
            - name: install java on runner
              uses: actions/setup-java@v5
              with:
                    java-version: '17'
                    distribution: 'temurin'
            - name: build java code
              run: mvn clean package
            - name: code coverage using sonarcloud
              run: mvn -B verify sonar:sonar -Dsonar.projectKey=sonar-qube-project_demo -Dsonar.organization=sonar-qube-project -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.token=$SONAR_TOKEN
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
